### ISSUE TITLE
Investigation of Watson Conversation Service on Dedicated Bluemix

### ISSUE THREAD

**Issue by mihui** [CognitiveBuild/Thoth#1]
- Check the access of creating a new Conversation Service on Dedicated Bluemix
- Investigate how to use Watson Conversation API in NodeJS and Java Run-time
- Discussion and finalize back-end solution

**Comment by mihui** [comment]
@chwangdl please work with Vincent and see if we have any blocks for this topic.

**Comment by chwangdl** [comment]
@mihui How i can contact with Vincent?What's his id?

**Comment by mihui** [comment]
He's id is @Hamasn here and zhouhdl is he's intranet id. To be specific to the 1st item of this task, check and see if the Dedicated Bluemix supports the "Workspace" of Conversation Service, otherwise it can't be used, the alternative plan is to use public trial Bluemix account.

**Comment by chwangdl** [comment]
@Hamasn I am wang chuanhe.very glad working with you.Now i researching the conversation service at public bluemix.I know some web front-end technologies about html,css and javascript but no experience about WPF and Winform.At back-end side i know some java and node.js.So what can i do for you?Are there any blocks about our topic above?

**Comment by mihui** [comment]
@CognitiveBuild/thoth we may have some options of back-end solution like:
- NodeJS
- Java

Seems everyone prefers nodejs?

**Comment by Hamasn** [comment]
@chwangdl Cool, really my honor to work with you. Maybe we could setup our back-end service first and then provide some RESTful service related to conversion dialog.
Haven't use the conversation service yet, and we could have a discussion tmr.

For me, I am iOS developer, know some basic knowledge of node.js and waston API,for front end, some basic js/html/css skill. 
Hope we could make the project success.

**Comment by mihui** [comment]
Anyone can create Conversation and use the workspace in dedicated Bluemix?

**Comment by mihui** [comment]
Dedicated Bluemix does not support Conversation yet, let's close this item.
