### ISSUE TITLE
Implement HTTP Client module to send asychronous requests to back-end RESTful service

### ISSUE THREAD

**Issue by mihui** [CognitiveBuild/Thoth#10]
This will enable the WPF client to invoke the RESTful services (Most of the requests should be GET and POST) implemented by NodeJS. Consider to create a common HTTP Client class for future extensions.

**Comment by yidlhu** [comment]
I am thinking maybe we can use System.Net.Http.HttpClient in c# to talk directly to watson service for sprint 1

**Comment by mihui** [comment]
Sure, that's good enough as long as it can keep contexts of conversation, so better to have a common class/method to "remember" and process those returned from JSON results. :)

**Comment by yidlhu** [comment]
I think this task is done~ pls try my code.

**Comment by mihui** [comment]
Yep, thanks for the update, @yidlhu , the code looks good too.

Only one comment, we're not going to use Watson Dialog Service as it's being deprecated and will be replaced by Watson Conversation Service, and also eventually we may have to use a NodeJS for bridging the requests between client and the Watson Conversation Service instead of directly talking to the Watson gateways, this will also secure and avoid hard-coding the credentials like this: https://github.com/CognitiveBuild/ThothWPF/blob/master/MainWindow.xaml.cs#L27 

So the code sample is good, can we keep this item open until we can use the Watson Conversation Service and build a simple Conversation proxy? Doing so we will change our code to point to the back-end RESTful service, back-end team will be responsible for it, but I have told Freddy to invite you all to the Dedicated Bluemix, you may work with the back-end team as well for integration purpose.

If we can't use the Conversation Service in a short time on Dedicated Bluemix, we may consider to use public trial account. I will discuss with back-end team too.

**Comment by mihui** [comment]
@CognitiveBuild/thoth The URL has been provided in Slack, please try to integrate the new service instead of Watson Dialog. Please read the API reference in [ThothNodeJS](https://github.com/CognitiveBuild/ThothNodeJS/blob/master/README.md)

**Comment by mihui** [comment]
This is good now, closing it.
