### ISSUE TITLE
Friendly crash or warning needed in case the webcam does not work

### ISSUE THREAD

**Issue by mihui** [CognitiveBuild/Thoth#28]
This kind of invalid query from camera will crash the application in the deployment machine without any logs or warning:

<img width="1022" alt="no-webcam" src="https://cloud.githubusercontent.com/assets/1511528/19548735/37ed3726-96db-11e6-994b-925a0dbab4ef.png">

**Comment by muchunchun** [comment]
We add the warning to solve the problem.If the device does not have any cameras installed  or the cameras does not work,the screen will show the message(The device does not start the camera normally)

**Comment by mihui** [comment]
Verified, closing.
