### ISSUE TITLE
Create Ogg/Opus codec wrapper for Speech-to-Text end-to-end streaming

### ISSUE THREAD

**Issue by mihui** [CognitiveBuild/Thoth#5]
Create Ogg/Opus codec wrapper (DLL/SubProject) for Speech-to-Text end-to-end streaming to reduce latency.

References: 
http://www.opus-codec.org/
https://wiki.xiph.org/OggOpus
http://www.ibm.com/watson/developercloud/doc/speech-to-text/websockets.shtml

**Comment by mihui** [comment]
The audio format needs to be: `audio/ogg;codecs=opus` for Watson Speech API to consume

**Comment by mihui** [comment]
@Hamasn , please investigate on this, port the C code as a wrapper for .NET projects. You may use the 3rd party WebSocket for testing, please consult with @yidlhu which WebSocket library you should use, then integrate with Microphone callback method to send out the encoded data stream.

**Comment by mihui** [comment]
Any updates guys?

**Comment by yidlhu** [comment]
can we put this task to next sprint? after we have all functions. working on adding text to speech function and show images/video function.

**Comment by yidlhu** [comment]
I found a opus/ogg solution on thothWPF, works good.
