### ISSUE TITLE
Create a simple user interface that displays Input field, microphone button and chat view

### ISSUE THREAD

**Issue by mihui** [CognitiveBuild/Thoth#9]
- Input field is for user to input the text they want to type
- Microphone is the final UI the visitor will interact with "Thoth", have an option to switch from Input field to Microphone and Microphone to Input field as settings for testing purpose
- Chat view is the area of displaying the history of the conversations. This area should be scroll-able, and also if the new conversation is coming, this area should scroll to the bottom to display the latest chat. This area will also have the ability to display picture in the future (e.g. like WeChat/QQ), so while implementing this area, please consider this compatibility, but it is not the scope of this sprint
- "Send" button (optional), it is only used for send prepared chat script
- Implement a responsive layout of these key components, because we may use voice command to invoke the other applications like "siri" or "goole now".

**Comment by mihui** [comment]
I have created a .NET solution on https://github.com/CognitiveBuild/ThothWPF, please continue to work on the microphone, including adding more UI components such as an option to switch between Microphone and Input field, and also optimizing the Chat view, like adding animations if possible. @wmxwang @muchunchun @yidlhu

**Comment by yidlhu** [comment]
yeah, that is great start. I have pushed latest code that has function talk with Watson.
